angular.module('InsiderOilApp', [
    'ngRoute', 
    'appRoutes', 
    'ngCookies',
    'flash',
    'autocomplete',
    'ngFileUpload',
    'ui.bootstrap',
    'textAngular',
    'ngSanitize',
    'elif',
    'ListOfInputsDirective',
    'PhotoBytesArray',
    'ProjectSearchDirective',
    'EditRecordFieldsDirective',
    'ListOfProjectsDirective',
    'FilteredObjectsDirective',
    'ManyToManyDirective'
]);