var db  = require('../db/models');
var tableViewParams = require('../lib/tableViewParams');
var fileUpload = require('../lib/fileUpload');
var importExcel = require('../lib/importExcel');
var dbUtils = require('../lib/dbUtils');

exports.main = function(req, res, next) {
    var modelName = req.query.table;
    model = db[modelName];
    dbUtils.findAllCustom(model).then(sendRecords).catch(onError);
    
    function sendRecords(records) {
        var viewParams = tableViewParams[modelName]();
        viewParams.gridFields.push('id');
        dbUtils.simplifyArray( model, records );
        var responseObj = {
            records: records,
            viewParams: viewParams
        };
        res.json( responseObj );
    }
    
    function onError(err) {
        console.log(err);
    }
}


exports.uploadFile = function(req, res, next) {
    fileUpload.receive( req, onFile, onFinish );

    function onFile(fileName, buf) {
        console.log( "File name: " + fileName );
        var model = req.query.table;
        importExcel(buf, model, onOk, onError);
        
        function onOk(status) {
            res.json( { status: status } );
        }
        
        function onError(err) {
            res.status(404).json( { errorMsg: err } );
        }
    }
      
    function onFinish() {
        console.log('Done parsing form!');
    };
}


function getModelFields(modelName) {
    var model = db[modelName];
    var viewParams = tableViewParams[modelName]();
    var fields = [];
    for(attribute in model.attributes) {
        if(model.attributes[attribute]._autoGenerated) continue;
        
        const att = viewParams.fields[attribute];
        if(!att) continue;
        var fieldLabel = att.label;
        fields.push( {
            name: attribute,
            label: fieldLabel,
            type: model.attributes[attribute].type.toString()
        } );
    }
    
    return fields;
}


exports.modelFields = function(req, res, next) {
    var modelName = req.query.model;
    var fields = getModelFields(modelName);
    res.json( { fields: fields } );
}


exports.recordValues = function(req, res, next) {
    var modelName = req.query.model;
    var id = req.query.id;
    var model = db[modelName];
    model.findById(id).then(onRecord).catch(onError);
    
    function onRecord(record) {
        var fields = getModelFields(modelName);
        res.json({ 
            values: record,
            fields: fields
        });
    }
    
    function onError(err) {
        res.status(404).json( { errorMsg: "Registro não encontrado" } );
    }
}


exports.createItem = function(req, res, next) {
    var newItemData = req.body.newItemData;
    var modelName = req.body.model;
    var model = db[modelName];     
    model.create(newItemData).then(onSave).catch(onError);
    
    function onSave() {
        res.json( { msg: "OK" } );
    }
    
    function onError(error) {
        res.status(404).json( { errorMsg: "Não foi possível criar o registro. " + error } );
    }
}


exports.saveItem = function(req, res, next) {
    var modelName = req.body.model;
    var recordData = req.body.record;
    var model = db[modelName];     
    model.findById( recordData.id ).then(onFindRecord).catch(onError);
    
    function onFindRecord(record) {
        for(attributeName in recordData)
            record[attributeName] = recordData[attributeName];
        record.save().then(onSave).catch(onError);
    }
    
    function onSave() {
        res.json( { msg: "OK" } );
    }
    
    function onError(error) {
        res.status(404).json( { errorMsg: "Não foi possível salvar o registro. " + error } );
    }
}


exports.deleteItem = function(req, res) {
    var id = req.query.id;
    var modelName = req.query.model;
    var model = db[modelName];     
    model.destroy({ where: { id: id } }).then( function() {
        res.json( { msg: "OK" } );
    }).catch( function(err) {
        res.status(404).json( { errorMsg: "Não foi possível apagar o registro. " + err } );
    });
}