import dbUtils = require("../dbUtils");
import { IField } from '../../../common/Interfaces';

interface IDataSourceOperations {
    getModelFields(modelName:string, includeAutogenerated?:boolean):IField[];
    addAttributesToRecord(record, attributes, dataSource);
    recordToViewValues(dataSourceName: string, record): any[];
}

export = IDataSourceOperations;