"use strict";

var db  = require('../db/models');
var tableViewParams = require('./tableViewParams');

function getAssociationOptions(model) {
    var includeOptions = [];
    for( var associationName in model.associations ) {
        const association = model.associations[associationName];
        includeOptions.push({ model: association.target, as: association.as });
    }
    return includeOptions;
}


exports.findAllCustom = function(model, options) {
    options = options ? options : {};
    options.include = getAssociationOptions(model);
    return model.findAll(options);
}


function simplifyItem(model, item) {
    for( var associationName in model.associations ) {
        const association = model.associations[associationName];
        for( var att in association.target.attributes ) {
            if(att == 'id') continue;
            const fieldName = association.as + '_' + att;
            item.dataValues[fieldName] = item[association.as][att];
        }
    }
}


exports.getModelFields = function(modelName) {
    var model = db[modelName];
    var viewParams = tableViewParams[modelName]();
    var fields = {};
    for(var attributeName in model.attributes) {
        if(model.attributes[attributeName]._autoGenerated) continue;
        
        const att = viewParams.fields[attributeName];
        if(!att) continue;
        fields[attributeName] = {
            label: att.label,
            type: model.attributes[attributeName].type.toString()
        };
    }
    
    for( var associationName in model.associations ) {
        const association = model.associations[associationName];
        const fieldName = association.identifierField;
        const att = viewParams.fields[fieldName];
        fields[fieldName] = {
            label: att.label,
            type: 'ref',
            model: association.target.name,
            association: associationName
        };
    }
    
    var fieldArray = [];
    for( var fieldName in fields ) {
        const obj = fields[fieldName];
        obj.name = fieldName;
        fieldArray.push(obj);
    }
    
    return fieldArray;
}


exports.simplifyArray = function(model, array) {
    for(var i = 0; i < array.length; i++) {
        simplifyItem( model, array[i] );
    }
}

exports.simplifyItem = simplifyItem;
exports.getAssociationOptions = getAssociationOptions;