import IDataSourceOperations = require('./IDataSourceOperations');
import BaseDataSourceOperations = require('./BaseDataSourceOperations');
import dsParams = require('../DataSourcesParams');

class Well implements IDataSourceOperations {
    getModelFields(modelName:string, includeAutogenerated?:boolean){
        let fields = BaseDataSourceOperations.getModelFieldsObj(modelName, includeAutogenerated);
        
        delete fields['drilling_rig_onshore_id'];
        delete fields['drilling_rig_offshore_id'];
        
        const params = dsParams['Well'];
        fields['drilling_rig'] = {
            label: params.fields['drilling_rig'].label,
            type: 'ref',
            model: 'AllDrillingRigs'
        };
        const fieldsArray = BaseDataSourceOperations.fieldsObjToArray(fields);
        return fieldsArray;
    }
    
    addAttributesToRecord(record, attributes, dataSource) {
        delete attributes['drilling_rig_offshore_id'];
        delete attributes['drilling_rig_onshore_id'];
        BaseDataSourceOperations.addAttributesToRecord(record, attributes, dataSource);
    }
}

const obj = new Well();
export = obj;