var db  = require('../db/models');
var tableViewParams = require('../lib/tableViewParams');
var fileUpload = require('../lib/fileUpload');
var importExcel = require('../lib/importExcel');

exports.main = function(req, res, next) {
    var model = req.query.table;
    db[model].findAll().then(sendRecords);
    
    function sendRecords(records) {
        var viewParams = tableViewParams[model]();
        viewParams.gridFields.push('id');
        var responseObj = {
            records: records,
            viewParams: viewParams
        };
        res.json( responseObj );
    }
}


exports.uploadFile = function(req, res, next) {
    fileUpload.receive( req, onFile, onFinish );

    function onFile(fileName, buf) {
        console.log( "File name: " + fileName );
        var model = req.query.table;
        importExcel(buf, model, onOk, onError);
        
        function onOk(status) {
            res.json( { status: status } );
        }
        
        function onError(err) {
            res.json( { errorMsg: err } );
        }
    }
      
    function onFinish() {
        console.log('Done parsing form!');
    };
}


exports.modelFields = function(req, res, next) {
    var modelName = req.query.model;
    var model = db[modelName];
    var viewParams = tableViewParams[modelName]();
    var fields = [];
    for(attribute in model.attributes) {
        if(model.attributes[attribute]._autoGenerated) continue;
        
        var fieldLabel = viewParams.fields[attribute].label;
        fields.push( {
            name: attribute,
            label: fieldLabel,
            type: model.attributes[attribute].type.toString()
        } );
    }
    res.json( { fields: fields } );
}


exports.recordValues = function(req, res, next) {
    var modelName = req.query.model;
    var id = req.query.id;
    var model = db[modelName];
    model.findById(id).then(onRecord).catch(onError);
    
    function onRecord(record) {
        res.json( { values: record } );
    }
    
    function onError(err) {
        res.status(404).json( { errorMsg: "Registro não encontrado" } );
    }
}


exports.createItem = function(req, res, next) {
    var newItemData = req.body.params.newItemData;
    var modelName = req.body.params.model;
    var model = db[modelName];     
    model.create(newItemData).then(onSave).catch(onError);
    
    function onSave() {
        res.json( { msg: "OK" } );
    }
    
    function onError(error) {
        res.status(404).json( { errorMsg: "Não foi possível criar o registro. " + error } );
    }
}


exports.deleteItem = function(req, res) {
    var id = req.query.id;
    var modelName = req.query.model;
    var model = db[modelName];     
    model.destroy({ where: { id: id } }).then( function() {
        res.json( { msg: "OK" } );
    }).catch( function(err) {
        res.status(404).json( { errorMsg: "Não foi possível apagar o registro. " + error } );
    });
}